import { Dictionary, File, TransformedToken } from 'style-dictionary/types';
import { A1TokenTypes } from '../../../shared/index.js';

/**
 * DISCLAIMER: This file has been generated using AI assistance.
 * The generation process was guided by the prompt specified in `.github/prompts/unit-testing.prompt.md`.
 */

// Mock file header lines returned by fileHeaderGenerator
export const mockFileHeaderLines = ['Generated by design-tokens-builder', 'Version: 1.0.0', 'Do not edit manually'];

/**
 * Factory function to create a basic mock TransformedToken
 */
export const createBasicToken = (overrides?: Partial<TransformedToken>): TransformedToken => {
	return {
		name: 'TEST_TOKEN_NAME',
		path: ['test', 'token', 'name'],
		original: {
			value: '#ffffff',
			type: 'color',
		},
		value: '#ffffff',
		$type: A1TokenTypes.color,
		attributes: {},
		filePath: 'tokens/test.json',
		isSource: true,
		...overrides,
	};
};

/**
 * Factory function to create a mock Dictionary
 */
export const createMockDictionary = (tokens: TransformedToken[]): Dictionary =>
	({
		allTokens: tokens,
		tokens: {},
		unfilteredTokens: {},
	}) as Dictionary;

/**
 * Factory function to create a mock File
 */
export const createMockFile = (destination: string = 'tokens.puml'): File =>
	({
		destination,
		format: 'a1/format/puml',
		options: {},
	}) as File;

// Test scenarios for format function
export const formatTestScenarios = [
	{
		description: 'single token',
		tokens: [createBasicToken()],
		expectedConstants: ['!$TEST_TOKEN_NAME = "#ffffff"'],
	},
	{
		description: 'multiple tokens',
		tokens: [
			createBasicToken({ name: 'color_primary', value: '#0066cc' }),
			createBasicToken({ name: 'color_secondary', value: '#ff6600' }),
		],
		expectedConstants: ['!$COLOR_PRIMARY = "#0066cc"', '!$COLOR_SECONDARY = "#ff6600"'],
	},
	{
		description: 'token with $value property',
		tokens: [createBasicToken({ $value: '#aabbcc' })],
		expectedConstants: ['!$TEST_TOKEN_NAME = "#aabbcc"'],
	},
];

// Edge case test scenarios
export const edgeCaseScenarios = [
	{
		description: 'empty token array',
		tokens: [],
		expectedConstants: [],
	},
	{
		description: 'token with undefined value',
		tokens: [createBasicToken({ value: undefined, $value: undefined })],
		expectedConstants: [],
	},
	{
		description: 'token with empty string value',
		tokens: [createBasicToken({ value: '' })],
		expectedConstants: [],
	},
	{
		description: 'token with null value',
		tokens: [createBasicToken({ value: null as unknown as string, $value: null as unknown as string })],
		expectedConstants: [],
	},
	{
		description: 'token with undefined name',
		tokens: [createBasicToken({ name: undefined })],
		expectedConstants: ['!$undefined = "#ffffff"'],
	},
	{
		description: 'mixed valid and invalid tokens',
		tokens: [
			createBasicToken({ name: 'valid_token', value: '#123456' }),
			createBasicToken({ value: undefined }),
			createBasicToken({ name: 'another_valid', value: '#abcdef' }),
		],
		expectedConstants: ['!$VALID_TOKEN = "#123456"', '!$ANOTHER_VALID = "#abcdef"'],
	},
];

// File structure test scenarios
export const fileStructureScenarios = [
	{
		description: 'default file destination',
		file: createMockFile(),
		expectedPathComment: '\ntokens.puml\n',
	},
	{
		description: 'custom file destination',
		file: createMockFile('output/custom-tokens.puml'),
		expectedPathComment: '\noutput/custom-tokens.puml\n',
	},
	{
		description: 'nested directory destination',
		file: createMockFile('dist/plantUML/theme-tokens.puml'),
		expectedPathComment: '\ndist/plantUML/theme-tokens.puml\n',
	},
];

// Token name variation test scenarios
export const tokenNameVariations = [
	{
		description: 'lowercase name',
		token: createBasicToken({ name: 'lowercase', value: '#111' }),
		expectedConstant: '!$LOWERCASE = "#111"',
	},
	{
		description: 'uppercase name',
		token: createBasicToken({ name: 'UPPERCASE', value: '#222' }),
		expectedConstant: '!$UPPERCASE = "#222"',
	},
	{
		description: 'mixed case name',
		token: createBasicToken({ name: 'MixedCase', value: '#333' }),
		expectedConstant: '!$MIXEDCASE = "#333"',
	},
	{
		description: 'name with underscores',
		token: createBasicToken({ name: 'token_with_underscores', value: '#666' }),
		expectedConstant: '!$TOKEN_WITH_UNDERSCORES = "#666"',
	},
	{
		description: 'name with numbers',
		token: createBasicToken({ name: 'token123', value: '#777' }),
		expectedConstant: '!$TOKEN123 = "#777"',
	},
];
