package com.escapp.mobile.ui

// ISO 3166-1 alpha-2 Country Codes - Vollständige Liste mit deutschen Namen
private val countryCodeToNameDe = mapOf(
    "AF" to "Afghanistan",
    "AX" to "Åland",
    "AL" to "Albanien",
    "DZ" to "Algerien",
    "AS" to "Amerikanisch-Samoa",
    "AD" to "Andorra",
    "AO" to "Angola",
    "AI" to "Anguilla",
    "AQ" to "Antarktis",
    "AG" to "Antigua und Barbuda",
    "AR" to "Argentinien",
    "AM" to "Armenien",
    "AW" to "Aruba",
    "AU" to "Australien",
    "AT" to "Österreich",
    "AZ" to "Aserbaidschan",
    "BS" to "Bahamas",
    "BH" to "Bahrain",
    "BD" to "Bangladesch",
    "BB" to "Barbados",
    "BY" to "Weißrussland",
    "BE" to "Belgien",
    "BZ" to "Belize",
    "BJ" to "Benin",
    "BM" to "Bermuda",
    "BT" to "Bhutan",
    "BO" to "Bolivien",
    "BQ" to "Bonaire, Sint Eustatius und Saba",
    "BA" to "Bosnien und Herzegowina",
    "BW" to "Botswana",
    "BV" to "Bouvetinsel",
    "BR" to "Brasilien",
    "IO" to "Britisches Territorium im Indischen Ozean",
    "VG" to "Britische Jungferninseln",
    "BN" to "Brunei",
    "BG" to "Bulgarien",
    "BF" to "Burkina Faso",
    "BI" to "Burundi",
    "CV" to "Cabo Verde",
    "KH" to "Kambodscha",
    "CM" to "Kamerun",
    "CA" to "Kanada",
    "KY" to "Kaimaninseln",
    "CF" to "Zentralafrikanische Republik",
    "TD" to "Tschad",
    "CL" to "Chile",
    "CN" to "China",
    "CX" to "Weihnachtsinsel",
    "CC" to "Kokosinseln",
    "CO" to "Kolumbien",
    "KM" to "Komoren",
    "CK" to "Cookinseln",
    "CR" to "Costa Rica",
    "HR" to "Kroatien",
    "CU" to "Kuba",
    "CW" to "Curacao",
    "CY" to "Zypern",
    "CZ" to "Czechia",
    "CD" to "Demokratische Republik Kongo",
    "DK" to "Dänemark",
    "DJ" to "Dschibuti",
    "DM" to "Dominica",
    "DO" to "Dominikanische Republik",
    "EC" to "Ecuador",
    "EG" to "Ägypten",
    "SV" to "El Salvador",
    "GQ" to "Äquatorialguinea",
    "ER" to "Eritrea",
    "EE" to "Estland",
    "SZ" to "Eswatini",
    "ET" to "Äthiopien",
    "FK" to "Falkland-Inseln",
    "FO" to "Färöer-Inseln",
    "FJ" to "Fidschi",
    "FI" to "Finnland",
    "FR" to "Frankreich",
    "GF" to "Französisch-Guayana",
    "PF" to "Französisch-Polynesien",
    "TF" to "Französische Süd- und Antarktisgebiete",
    "GA" to "Gabun",
    "GM" to "Gambia",
    "GE" to "Georgien",
    "DE" to "Deutschland",
    "GH" to "Ghana",
    "GI" to "Gibraltar",
    "GR" to "Griechenland",
    "GL" to "Grönland",
    "GD" to "Grenada",
    "GP" to "Guadeloupe",
    "GU" to "Guam",
    "GT" to "Guatemala",
    "GG" to "Guernsey",
    "GN" to "Guinea",
    "GW" to "Guinea-Bissau",
    "GY" to "Guyana",
    "HT" to "Haiti",
    "HM" to "Heard und McDonaldinseln",
    "HN" to "Honduras",
    "HK" to "Hongkong",
    "HU" to "Ungarn",
    "IS" to "Island",
    "IN" to "Indien",
    "ID" to "Indonesien",
    "IR" to "Iran",
    "IQ" to "Irak",
    "IE" to "Irland",
    "IM" to "Isle of Man",
    "IL" to "Israel",
    "IT" to "Italien",
    "CI" to "Elfenbeinküste",
    "JM" to "Jamaika",
    "JP" to "Japan",
    "JE" to "Jersey",
    "JO" to "Jordanien",
    "KZ" to "Kasachstan",
    "KE" to "Kenia",
    "KI" to "Kiribati",
    "XK" to "Kosovo",
    "KW" to "Kuwait",
    "KG" to "Kirgisistan",
    "LA" to "Laos",
    "LV" to "Lettland",
    "LB" to "Libanon",
    "LS" to "Lesotho",
    "LR" to "Liberia",
    "LY" to "Libyen",
    "LI" to "Liechtenstein",
    "LT" to "Litauen",
    "LU" to "Luxemburg",
    "MO" to "Macao",
    "MG" to "Madagaskar",
    "MW" to "Malawi",
    "MY" to "Malaysia",
    "MV" to "Malediven",
    "ML" to "Mali",
    "MT" to "Malta",
    "MH" to "Marshallinseln",
    "MQ" to "Martinique",
    "MR" to "Mauretanien",
    "MU" to "Mauritius",
    "YT" to "Mayotte",
    "MX" to "Mexiko",
    "FM" to "Mikronesien",
    "MD" to "Moldau",
    "MC" to "Monaco",
    "MN" to "Mongolei",
    "ME" to "Montenegro",
    "MS" to "Montserrat",
    "MA" to "Marokko",
    "MZ" to "Mosambik",
    "MM" to "Myanmar",
    "NA" to "Namibia",
    "NR" to "Nauru",
    "NP" to "Nepal",
    "AN" to "Niederländische Antillen",
    "NL" to "The Netherlands",
    "NC" to "Neukaledonien",
    "NZ" to "Neuseeland",
    "NI" to "Nicaragua",
    "NE" to "Niger",
    "NG" to "Nigeria",
    "NU" to "Niue",
    "NF" to "Norfolkinsel",
    "KP" to "Nordkorea",
    "MK" to "North Macedonia",
    "MP" to "Nördliche Marianen",
    "NO" to "Norwegen",
    "OM" to "Oman",
    "PK" to "Pakistan",
    "PW" to "Palau",
    "PS" to "Palästinensische Autonomiegebiete",
    "PA" to "Panama",
    "PG" to "Papua-Neuguinea",
    "PY" to "Paraguay",
    "PE" to "Peru",
    "PH" to "Philippinen",
    "PN" to "Pitcairninseln",
    "PL" to "Polen",
    "PT" to "Portugal",
    "PR" to "Puerto Rico",
    "QA" to "Katar",
    "CG" to "Republik Kongo",
    "RE" to "Réunion",
    "RO" to "Rumänien",
    "RU" to "Russland",
    "RW" to "Ruanda",
    "BL" to "Saint-Barthélemy",
    "SH" to "St. Helena",
    "KN" to "St. Kitts und Nevis",
    "LC" to "St. Lucia",
    "MF" to "St. Martin",
    "PM" to "Saint-Pierre und Miquelon",
    "VC" to "St. Vincent und die Grenadinen",
    "WS" to "Samoa",
    "SM" to "San Marino",
    "ST" to "São Tomé und Príncipe",
    "SA" to "Saudi-Arabien",
    "SN" to "Senegal",
    "RS" to "Serbien",
    "CS" to "Serbien und Montenegro",
    "SC" to "Seychellen",
    "SL" to "Sierra Leone",
    "SG" to "Singapur",
    "SX" to "Sint Maarten",
    "SK" to "Slowakei",
    "SI" to "Slowenien",
    "SB" to "Salomon-Inseln",
    "SO" to "Somalia",
    "ZA" to "Südafrika",
    "GS" to "Südgeorgien und die Südlichen Sandwichinseln",
    "KR" to "Südkorea",
    "SS" to "Südsudan",
    "ES" to "Spanien",
    "LK" to "Sri Lanka",
    "SD" to "Sudan",
    "SR" to "Suriname",
    "SJ" to "Svalbard und Jan Mayen",
    "SE" to "Schweden",
    "CH" to "Schweiz",
    "SY" to "Syrien",
    "TW" to "Taiwan",
    "TJ" to "Tadschikistan",
    "TZ" to "Tansania",
    "TH" to "Thailand",
    "TL" to "Timor Leste",
    "TG" to "Togo",
    "TK" to "Tokelau",
    "TO" to "Tonga",
    "TT" to "Trinidad und Tobago",
    "TN" to "Tunesien",
    "TR" to "Türkei",
    "TM" to "Turkmenistan",
    "TC" to "Turks- und Caicosinseln",
    "TV" to "Tuvalu",
    "VI" to "Amerikanische Jungferninseln",
    "UG" to "Uganda",
    "UA" to "Ukraine",
    "AE" to "Vereinte Arabische Emirate",
    "GB" to "Großbritannien",
    "US" to "Vereinigte Staaten von Amerika (USA)",
    "UM" to "United States Minor Outlying Islands",
    "UY" to "Uruguay",
    "UZ" to "Usbekistan",
    "VU" to "Vanuatu",
    "VA" to "Vatikanstadt",
    "VE" to "Venezuela",
    "VN" to "Vietnam",
    "WF" to "Wallis und Futuna",
    "EH" to "Westsahara",
    "YE" to "Jemen",
    "ZM" to "Sambia",
    "ZW" to "Simbabwe"
)

fun getCountryNameDe(code: String?): String {
    val normalized = code?.trim()?.uppercase().orEmpty()
    if (normalized.isEmpty()) return "Unbekannt"
    return countryCodeToNameDe[normalized] ?: normalized
}
