/* eslint-disable @typescript-eslint/naming-convention */
import { TokenSetStatus } from '@tokens-studio/types';
import { tokensSsotFolder } from '../../shared/index.js';

/**
 * DISCLAIMER: This file has been generated using AI assistance.
 * The generation process was guided by the prompt specified in `.github/prompts/unit-testing.prompt.md`.
 */

export const selectedTokenSetsUnsorted: Record<string, TokenSetStatus> = {
	'components/default/radio-button': TokenSetStatus.ENABLED,
	'components/default/avatar': TokenSetStatus.ENABLED,
	'components/default/divider': TokenSetStatus.ENABLED,
	'components/default/dropdown': TokenSetStatus.ENABLED,
	'components/default/accordion': TokenSetStatus.ENABLED,
	'components/default/tab-m': TokenSetStatus.ENABLED,
	'components/default/form-field': TokenSetStatus.ENABLED,
	'components/default/icon': TokenSetStatus.ENABLED,
	'components/default/list': TokenSetStatus.ENABLED,
	'components/default/button': TokenSetStatus.ENABLED,
	'components/default/segmented-control': TokenSetStatus.ENABLED,
	'components/default/badge': TokenSetStatus.ENABLED,
	'components/default/switch': TokenSetStatus.ENABLED,
	'partials/default/indicator': TokenSetStatus.ENABLED,
	'partials/dense/indicator': TokenSetStatus.ENABLED,
	'semantic/color-schemes/dark': TokenSetStatus.SOURCE,
	'components/default/tab': TokenSetStatus.ENABLED,
	'components/dense/tab': TokenSetStatus.ENABLED,
	'components/default/tag': TokenSetStatus.ENABLED,
	'components/default/tile': TokenSetStatus.ENABLED,
	'components/default/toggle-button': TokenSetStatus.ENABLED,
	'core/colors': TokenSetStatus.SOURCE,
	'core/grid': TokenSetStatus.SOURCE,
	'core/motion': TokenSetStatus.SOURCE,
	'core/typography': TokenSetStatus.SOURCE,
	'partials/default/info': TokenSetStatus.ENABLED,
	'partials/default/input-field': TokenSetStatus.ENABLED,
	'semantic/color-schemes/light': TokenSetStatus.SOURCE,
	'semantic/combined/composites': TokenSetStatus.SOURCE,
	'semantic/densities/compact-m': TokenSetStatus.SOURCE,
	'core/dimensions': TokenSetStatus.SOURCE,
	'semantic/densities/compact': TokenSetStatus.SOURCE,
	'semantic/densities/compact-l': TokenSetStatus.SOURCE,
	'semantic/densities/dense-l': TokenSetStatus.SOURCE,
	'semantic/densities/dense-m': TokenSetStatus.SOURCE,
	'semantic/motion/minimal': TokenSetStatus.SOURCE,
	'semantic/densities/dense': TokenSetStatus.SOURCE,
	'semantic/densities/spacious-l': TokenSetStatus.SOURCE,
	'semantic/densities/spacious': TokenSetStatus.SOURCE,
	'semantic/densities/spacious-m': TokenSetStatus.SOURCE,
	'semantic/motion/lively': TokenSetStatus.SOURCE,
};

export const selectedTokenSetsSorted: Record<string, TokenSetStatus> = {
	'core/colors': TokenSetStatus.SOURCE,
	'core/dimensions': TokenSetStatus.SOURCE,
	'core/grid': TokenSetStatus.SOURCE,
	'core/motion': TokenSetStatus.SOURCE,
	'core/typography': TokenSetStatus.SOURCE,
	'semantic/color-schemes/light': TokenSetStatus.SOURCE,
	'semantic/color-schemes/dark': TokenSetStatus.SOURCE,
	'semantic/densities/spacious': TokenSetStatus.SOURCE,
	'semantic/densities/spacious-m': TokenSetStatus.SOURCE,
	'semantic/densities/spacious-l': TokenSetStatus.SOURCE,
	'semantic/densities/compact': TokenSetStatus.SOURCE,
	'semantic/densities/compact-m': TokenSetStatus.SOURCE,
	'semantic/densities/compact-l': TokenSetStatus.SOURCE,
	'semantic/densities/dense': TokenSetStatus.SOURCE,
	'semantic/densities/dense-m': TokenSetStatus.SOURCE,
	'semantic/densities/dense-l': TokenSetStatus.SOURCE,
	'semantic/motion/lively': TokenSetStatus.SOURCE,
	'semantic/motion/minimal': TokenSetStatus.SOURCE,
	'semantic/combined/composites': TokenSetStatus.SOURCE,
	'partials/default/indicator': TokenSetStatus.ENABLED,
	'partials/default/info': TokenSetStatus.ENABLED,
	'partials/default/input-field': TokenSetStatus.ENABLED,
	'components/default/accordion': TokenSetStatus.ENABLED,
	'components/default/avatar': TokenSetStatus.ENABLED,
	'components/default/badge': TokenSetStatus.ENABLED,
	'components/default/button': TokenSetStatus.ENABLED,
	'components/default/divider': TokenSetStatus.ENABLED,
	'components/default/dropdown': TokenSetStatus.ENABLED,
	'components/default/form-field': TokenSetStatus.ENABLED,
	'components/default/icon': TokenSetStatus.ENABLED,
	'components/default/list': TokenSetStatus.ENABLED,
	'components/default/radio-button': TokenSetStatus.ENABLED,
	'components/default/segmented-control': TokenSetStatus.ENABLED,
	'components/default/switch': TokenSetStatus.ENABLED,
	'components/default/tab': TokenSetStatus.ENABLED,
	'components/default/tag': TokenSetStatus.ENABLED,
	'components/default/tile': TokenSetStatus.ENABLED,
	'components/default/toggle-button': TokenSetStatus.ENABLED,
	'components/default/tab-m': TokenSetStatus.ENABLED,
	'partials/dense/indicator': TokenSetStatus.ENABLED,
	'components/dense/tab': TokenSetStatus.ENABLED,
};

export const ssotTokenSetFilePathsUnsorted: string[] = [
	'tokens/$themes.json',
	'tokens/components/default/divider.json',
	'tokens/components/default/button.json',
	'tokens/components/default/badge.json',
	'tokens/$metadata.json',
	'tokens/semantic/densities/spacious.json',
	'tokens/semantic/densities/spacious-m.json',
	'tokens/partials/default/input-field.json',
	'tokens/partials/default/info.json',
	'tokens/semantic/densities/spacious-l.json',
	'tokens/semantic/color-schemes/dark.json',
	'tokens/semantic/densities/dense.json',
	'tokens/semantic/densities/dense-m.json',
	'tokens/semantic/densities/dense-l.json',
	'tokens/core/motion.json',
	'tokens/semantic/densities/compact.json',
	'tokens/semantic/densities/compact-l.json',
	'tokens/semantic/motion/minimal.json',
	'tokens/core/typography.json',
	'tokens/semantic/motion/lively.json',
	'tokens/semantic/combined/composites.json',
	'tokens/semantic/color-schemes/light.json',
	'tokens/partials/dense/indicator.json',
	'tokens/core/colors.json',
	'tokens/components/default/toggle-button.json',
	'tokens/components/default/tile.json',
	'tokens/components/dense/tab.json',
	'tokens/components/default/tag.json',
	'tokens/core/grid.json',
	'tokens/components/default/tab-m.json',
	'tokens/components/default/tab.json',
	'tokens/components/default/switch.json',
	'tokens/components/default/segmented-control.json',
	'tokens/core/dimensions.json',
	'tokens/components/default/radio-button.json',
	'tokens/components/default/list.json',
	'tokens/components/default/icon.json',
	'tokens/partials/default/indicator.json',
	'tokens/components/default/form-field.json',
	'tokens/components/default/dropdown.json',
	'tokens/components/default/avatar.json',
	'tokens/components/default/accordion.json',
	'tokens/semantic/densities/compact-m.json',
];

export const ssotTokenSetFilePathsSorted: string[] = [
	'tokens/core/colors.json',
	'tokens/core/dimensions.json',
	'tokens/core/grid.json',
	'tokens/core/motion.json',
	'tokens/core/typography.json',
	'tokens/semantic/color-schemes/light.json',
	'tokens/semantic/color-schemes/dark.json',
	'tokens/semantic/densities/spacious.json',
	'tokens/semantic/densities/spacious-m.json',
	'tokens/semantic/densities/spacious-l.json',
	'tokens/semantic/densities/compact.json',
	'tokens/semantic/densities/compact-m.json',
	'tokens/semantic/densities/compact-l.json',
	'tokens/semantic/densities/dense.json',
	'tokens/semantic/densities/dense-m.json',
	'tokens/semantic/densities/dense-l.json',
	'tokens/semantic/motion/lively.json',
	'tokens/semantic/motion/minimal.json',
	'tokens/semantic/combined/composites.json',
	'tokens/partials/default/indicator.json',
	'tokens/partials/default/info.json',
	'tokens/partials/default/input-field.json',
	'tokens/components/default/accordion.json',
	'tokens/components/default/avatar.json',
	'tokens/components/default/badge.json',
	'tokens/components/default/button.json',
	'tokens/components/default/divider.json',
	'tokens/components/default/dropdown.json',
	'tokens/components/default/form-field.json',
	'tokens/components/default/icon.json',
	'tokens/components/default/list.json',
	'tokens/components/default/radio-button.json',
	'tokens/components/default/segmented-control.json',
	'tokens/components/default/switch.json',
	'tokens/components/default/tab.json',
	'tokens/components/default/tag.json',
	'tokens/components/default/tile.json',
	'tokens/components/default/toggle-button.json',
	'tokens/components/default/tab-m.json',
	'tokens/partials/dense/indicator.json',
	'tokens/components/dense/tab.json',
	'tokens/$metadata.json',
	'tokens/$themes.json',
];

const pathDelimiter = '/';
const getIndexForLayer = (sortedPaths: string[], subPath: string) =>
	sortedPaths.findIndex(path => path.startsWith(`${subPath}${pathDelimiter}`));
export const getSelectedTokenSetIndexForLayer = (sortedPaths: string[], layer: string) => getIndexForLayer(sortedPaths, layer);
export const getSsotTokenSetIndexForLayer = (sortedPaths: string[], layer: string) => {
	const path = `${tokensSsotFolder}${pathDelimiter}${layer}`;
	return getIndexForLayer(sortedPaths, path);
};
