import { BraceType } from '../responsive-integration/enums/index.js';
import { ScssMixinFileProcessingData, ScssMixinProcessingState } from '../responsive-integration/types/index.js';

/**
 * DISCLAIMER: This file has been generated using AI assistance.
 * The generation process was guided by the prompt specified in `.github/prompts/unit-testing.prompt.md`.
 */

// Mock target folder and parameters
export const mockBrand = 'escapp';
export const mockDesignSystemName = 'a1';
export const mockTargetFolder = `token-package/dist/${mockBrand}/${mockDesignSystemName}/web`;

// Mock file paths and names
export const mockCssFilePath = mockTargetFolder + '/test-file-name-here.css';
export const mockScssFilePath = mockTargetFolder + '/test-file-name-here-mixins.scss';
export const mockFileName = 'test-file-name-here.css';
export const mockFileNameWithoutExtension = 'test-file-name-here';
export const mockMixinName = 'design-test-file-name-here';

export const mockCssFilePathWithTwoDashes = mockTargetFolder + '/test-file.css';
export const mockCssFilePathWithFourDashes = mockTargetFolder + '/test-file-name-here-extra.css';
export const mockNonCssFilePath = mockTargetFolder + '/test-file-name-here.json';

// Mock file processing data
export const mockFileProcessingData: ScssMixinFileProcessingData = {
	filePath: mockCssFilePath,
	fileName: mockFileName,
	fileNameWithoutExtension: mockFileNameWithoutExtension,
	scssFilePath: mockScssFilePath,
	mixinName: mockMixinName,
};

// Mock processing state
export const mockInitialProcessingState: ScssMixinProcessingState = {
	insideMediaQuery: false,
	addedBlankLineBeforeMediaQuery: false,
	braceStack: [],
};

export const mockProcessingStateInsideMediaQuery: ScssMixinProcessingState = {
	insideMediaQuery: true,
	addedBlankLineBeforeMediaQuery: true,
	braceStack: [BraceType.media],
};

export const mockProcessingStateWithSelectorInMedia: ScssMixinProcessingState = {
	insideMediaQuery: true,
	addedBlankLineBeforeMediaQuery: true,
	braceStack: [BraceType.media, BraceType.selectorInMedia],
};

export const mockProcessingStateWithSelector: ScssMixinProcessingState = {
	insideMediaQuery: false,
	addedBlankLineBeforeMediaQuery: false,
	braceStack: [BraceType.selector],
};

// Mock CSS content lines
export const mockCssLinesWithHeader = [
	'/*',
	' * CSS Generated by Style Dictionary',
	' * https://amzn.github.io/style-dictionary/',
	' */',
	':root, :host {',
	'  --color-primary: #0066cc;',
	'  --color-secondary: #999999;',
	'}',
];

export const mockCssLinesWithoutHeader = [':root, :host {', '  --color-primary: #0066cc;', '  --color-secondary: #999999;', '}'];

export const mockCssLinesWithMediaQuery = [
	'/*',
	' * CSS Generated by Style Dictionary',
	' */',
	':root, :host {',
	'  --color-primary: #0066cc;',
	'}',
	'@media (min-width: 768px) {',
	'  :root, :host {',
	'    --color-primary: #0088ff;',
	'  }',
	'}',
];

export const mockCssLinesEmpty: string[] = [];

export const mockCssLinesOnlyComment = ['/*', ' * CSS Generated by Style Dictionary', ' */'];

export const mockCssLinesComplexStructure = [
	'/*',
	' * CSS Generated by Style Dictionary',
	' */',
	'',
	':root, :host {',
	'  --color-primary: #0066cc;',
	'  --font-size-base: 16px;',
	'}',
	'',
	'@media (min-width: 768px) {',
	'  :root, :host {',
	'    --color-primary: #0088ff;',
	'    --font-size-base: 18px;',
	'  }',
	'}',
	'',
	'@media (min-width: 1024px) {',
	'  :root, :host {',
	'    --color-primary: #00aaff;',
	'  }',
	'}',
];

export const mockCssLinesNoHeaderComment = [':root, :host {', '  --color-primary: #0066cc;', '}'];

// Mock header and content line separation results
export const mockHeaderLines = ['/*', ' * CSS Generated by Style Dictionary', ' * https://amzn.github.io/style-dictionary/', ' */'];

export const mockContentLines = [':root, :host {', '  --color-primary: #0066cc;', '  --color-secondary: #999999;', '}'];

// Mock file lists
export const mockAllFiles = [
	mockTargetFolder + '/test-file-name-here.css',
	mockTargetFolder + '/another-test-file-name.css',
	mockTargetFolder + '/wrong-dash-count.css',
	mockTargetFolder + '/test-file.json',
	mockTargetFolder + '/valid-file-name-extension.css',
];

export const mockCssFiles = [
	mockTargetFolder + '/test-file-name-here.css',
	mockTargetFolder + '/another-test-file-name.css',
	mockTargetFolder + '/wrong-dash-count.css',
	mockTargetFolder + '/valid-file-name-extension.css',
];

export const mockFilteredCssFiles = [
	mockTargetFolder + '/test-file-name-here.css',
	mockTargetFolder + '/another-test-file-name.css',
	mockTargetFolder + '/valid-file-name-extension.css',
];

// Mock SCSS content output
export const mockExpectedScssContent = `/*
 * CSS Generated by Style Dictionary
 * https://amzn.github.io/style-dictionary/
 */

@mixin a1-design-test-file-name-here($selector) {
	#{$selector} {
		--color-primary: #0066cc;
		--color-secondary: #999999;
	}
}`;

export const mockExpectedScssContentWithMediaQuery = `/*
 * CSS Generated by Style Dictionary
 */

@mixin a1-design-test-file-name-here($selector) {
	#{$selector} {
		--color-primary: #0066cc;
	}

	@media (min-width: 768px) {
		#{$selector} {
			--color-primary: #0088ff;
		}
	}
}`;
