import { Config } from 'style-dictionary/types';

/**
 * DISCLAIMER: This file has been generated using AI assistance.
 * The generation process was guided by the prompt specified in `.github/prompts/unit-testing.prompt.md`.
 */

// Mock values for dependencies
export const mockVersionFileHeaderPlaceholder = '§§{VERSION_PLACEHOLDER}§§';
export const mockCreateDateFileHeaderPlaceholder = '§§{DATE_PLACEHOLDER}§§';
export const mockAllianzFileHeaderName = 'allianzFileHeader';

/**
 * Mock Config object for testing FileHeader function
 */
export const createMockConfig = (): Config => {
	return {
		source: ['tokens/**/*.json'],
		platforms: {
			web: {
				transformGroup: 'web',
				buildPath: 'build/web/',
				files: [
					{
						destination: 'tokens.css',
						format: 'css/variables',
					},
				],
			},
		},
	};
};

/**
 * Mock Config object with minimal properties
 */
export const createMinimalMockConfig = (): Config => {
	return {
		source: [],
		platforms: {},
	};
};

/**
 * Mock Config object with extensive properties
 */
export const createExtensiveMockConfig = (): Config => {
	return {
		source: ['tokens/**/*.json'],
		platforms: {
			web: {
				transformGroup: 'web',
				buildPath: 'build/web/',
				files: [
					{
						destination: 'tokens.css',
						format: 'css/variables',
					},
				],
			},
			ios: {
				transformGroup: 'ios',
				buildPath: 'build/ios/',
				files: [
					{
						destination: 'Tokens.swift',
						format: 'ios-swift/class.swift',
					},
				],
			},
		},
	};
};

/**
 * Expected file header output for standard scenario
 */
export const createExpectedStandardFileHeader = (): string[] => [
	`THIS FILE WAS GENERATED AUTOMATICALLY AND SHOULD NOT BE EDITED MANUALLY!`,
	``,
	`Version ${mockVersionFileHeaderPlaceholder}`,
	`Generated on ${mockCreateDateFileHeaderPlaceholder}`,
	`Copyright (c) Allianz Group`,
	'',
	'DISCLAIMER: While this major version represents a significant milestone in stability and',
	'reliability, the Allianz A1 Design Tokens will continue to evolve. We are committed to',
	'regularly expanding our A1 Design Token library to support additional components and use',
	'cases. Our versioning strategy follows semantic versioning principles, with major releases',
	'scheduled biannually to ensure predictability and minimize disruption to your projects.',
];

/**
 * Scenario factory for standard file header generation
 */
export const createStandardFileHeaderScenario = () => {
	return {
		defaultMessage: undefined,
		options: undefined,
		description: 'Standard file header generation with no parameters',
	};
};

/**
 * Scenario factory for file header generation with default message
 */
export const createFileHeaderWithDefaultMessageScenario = () => {
	return {
		defaultMessage: ['Generated by Style Dictionary', 'Do not edit directly'],
		options: undefined,
		description: 'File header generation with default message parameter',
	};
};

/**
 * Scenario factory for file header generation with options
 */
export const createFileHeaderWithOptionsScenario = () => {
	return {
		defaultMessage: undefined,
		options: createMockConfig(),
		description: 'File header generation with options parameter',
	};
};

/**
 * Scenario factory for file header generation with both parameters
 */
export const createFileHeaderWithBothParametersScenario = () => {
	return {
		defaultMessage: ['Style Dictionary Generated File', 'Version 1.0.0'],
		options: createExtensiveMockConfig(),
		description: 'File header generation with both defaultMessage and options',
	};
};

/**
 * Scenario factory for file header generation with empty default message
 */
export const createFileHeaderWithEmptyDefaultMessageScenario = () => {
	return {
		defaultMessage: [],
		options: undefined,
		description: 'File header generation with empty default message array',
	};
};

/**
 * Scenario factory for file header generation with null default message
 */
export const createFileHeaderWithNullDefaultMessageScenario = () => {
	return {
		defaultMessage: null as unknown as string[],
		options: undefined,
		description: 'File header generation with null default message',
	};
};

/**
 * Scenario factory for file header generation with undefined options
 */
export const createFileHeaderWithUndefinedOptionsScenario = () => {
	return {
		defaultMessage: ['Test message'],
		options: undefined,
		description: 'File header generation with explicitly undefined options',
	};
};

/**
 * Scenario factory for file header generation with minimal config
 */
export const createFileHeaderWithMinimalConfigScenario = () => {
	return {
		defaultMessage: undefined,
		options: createMinimalMockConfig(),
		description: 'File header generation with minimal config object',
	};
};

/**
 * Scenario factory for file header generation with extensive config
 */
export const createFileHeaderWithExtensiveConfigScenario = () => {
	return {
		defaultMessage: ['Header message'],
		options: createExtensiveMockConfig(),
		description: 'File header generation with extensive config object',
	};
};
