import { ThemeObject, TokenSetStatus } from '@tokens-studio/types';
import { ThemeGroups } from '../../../../shared/index.js';

/**
 * DISCLAIMER: This file has been generated using AI assistance.
 * The generation process was guided by the prompt specified in `.github/prompts/unit-testing.prompt.md`.
 */

/* eslint-disable @typescript-eslint/naming-convention */

// Mock theme data representing the input to theme combinator
export const mockDensityThemes: ThemeObject[] = [
	{
		id: 'density-spacious-xs-s',
		name: 'Spacious XS-S',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'density-spacious-m',
		name: 'Spacious M',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/spacious-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'density-spacious-l-3xl',
		name: 'Spacious L-3XL',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/spacious-m': TokenSetStatus.ENABLED,
			'semantic/densities/spacious-l': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'density-compact-xs-s',
		name: 'Compact XS-S',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'density-compact-m',
		name: 'Compact M',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/compact-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'density-compact-l-3xl',
		name: 'Compact L-3XL',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/compact-m': TokenSetStatus.ENABLED,
			'semantic/densities/compact-l': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'density-dense-xs-s',
		name: 'Dense XS-S',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/dense': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'density-dense-m',
		name: 'Dense M',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/dense': TokenSetStatus.ENABLED,
			'semantic/densities/dense-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'density-dense-l-3xl',
		name: 'Dense L-3XL',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/dense': TokenSetStatus.ENABLED,
			'semantic/densities/dense-m': TokenSetStatus.ENABLED,
			'semantic/densities/dense-l': TokenSetStatus.ENABLED,
		},
	},
];

export const mockComponentThemes: ThemeObject[] = [
	{
		id: 'component-spacious-xs-s',
		name: 'Spacious XS-S',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-spacious-m',
		name: 'Spacious M',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/densities/spacious-m': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-spacious-l-3xl',
		name: 'Spacious L-3XL',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/densities/spacious-m': TokenSetStatus.SOURCE,
			'semantic/densities/spacious-l': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-compact-xs-s',
		name: 'Compact XS-S',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/densities/compact': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-compact-m',
		name: 'Compact M',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/densities/compact': TokenSetStatus.SOURCE,
			'semantic/densities/compact-m': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-compact-l-3xl',
		name: 'Compact L-3XL',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/densities/compact': TokenSetStatus.SOURCE,
			'semantic/densities/compact-m': TokenSetStatus.SOURCE,
			'semantic/densities/compact-l': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-dense-xs-s',
		name: 'Dense XS-S',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/densities/compact': TokenSetStatus.SOURCE,
			'semantic/densities/dense': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-dense-m',
		name: 'Dense M',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/densities/compact': TokenSetStatus.SOURCE,
			'semantic/densities/dense': TokenSetStatus.SOURCE,
			'semantic/densities/dense-m': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-dense-l-3xl',
		name: 'Dense L-3XL',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/densities/compact': TokenSetStatus.SOURCE,
			'semantic/densities/dense': TokenSetStatus.SOURCE,
			'semantic/densities/dense-m': TokenSetStatus.SOURCE,
			'semantic/densities/dense-l': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
];

// Mock themes for other groups (Core, Color-Schemes, Motion, etc.)
export const mockOtherThemes: ThemeObject[] = [
	{
		id: 'core-theme',
		name: 'Core',
		group: ThemeGroups.core,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.ENABLED,
			'core/dimensions': TokenSetStatus.ENABLED,
			'core/grid': TokenSetStatus.ENABLED,
			'core/motion': TokenSetStatus.ENABLED,
			'core/typography': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'light-theme',
		name: 'Light',
		group: ThemeGroups.colorSchemes,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'dark-theme',
		name: 'Dark',
		group: ThemeGroups.colorSchemes,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.ENABLED,
			'semantic/color-schemes/dark': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'lively-theme',
		name: 'Lively',
		group: ThemeGroups.motion,
		selectedTokenSets: {
			'core/motion': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'composites-theme',
		name: 'Composites',
		group: ThemeGroups.composites,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.ENABLED,
		},
	},
];

// Complete mock input theme data
export const mockInputThemes: ThemeObject[] = [...mockOtherThemes, ...mockDensityThemes, ...mockComponentThemes];

// Mock expected combined themes that should be generated
export const expectedCombinedThemes: ThemeObject[] = [
	{
		id: 'Spacious-XS-00',
		name: 'Spacious-XS',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'Spacious-M-11',
		name: 'Spacious-M',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/spacious-m': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'Spacious-L-22',
		name: 'Spacious-L',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/spacious-m': TokenSetStatus.ENABLED,
			'semantic/densities/spacious-l': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'Compact-XS-33',
		name: 'Compact-XS',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'Compact-M-44',
		name: 'Compact-M',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/compact-m': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'Compact-L-55',
		name: 'Compact-L',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/compact-m': TokenSetStatus.ENABLED,
			'semantic/densities/compact-l': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'Dense-XS-66',
		name: 'Dense-XS',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/dense': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'Dense-M-77',
		name: 'Dense-M',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/dense': TokenSetStatus.ENABLED,
			'semantic/densities/dense-m': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'Dense-L-88',
		name: 'Dense-L',
		group: ThemeGroups.componentDensities,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
			'semantic/densities/compact': TokenSetStatus.ENABLED,
			'semantic/densities/dense': TokenSetStatus.ENABLED,
			'semantic/densities/dense-m': TokenSetStatus.ENABLED,
			'semantic/densities/dense-l': TokenSetStatus.ENABLED,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
		},
	},
];

// Mock themes with breakpoint-specific token sets for testing filtering logic
export const mockThemeWithBreakpointTokenSets: ThemeObject = {
	id: 'test-breakpoint-theme',
	name: 'Test Breakpoint Theme',
	group: ThemeGroups.components,
	selectedTokenSets: {
		'core/colors': TokenSetStatus.SOURCE,
		'core/dimensions': TokenSetStatus.SOURCE,
		'components/default/button': TokenSetStatus.ENABLED,
		'components/default/tab-xs': TokenSetStatus.ENABLED,
		'components/default/tab-s': TokenSetStatus.ENABLED,
		'components/default/tab-m': TokenSetStatus.ENABLED,
		'components/default/tab-l': TokenSetStatus.ENABLED,
		'components/default/tab-xl': TokenSetStatus.ENABLED,
		'components/default/tab-2xl': TokenSetStatus.ENABLED,
		'components/default/tab-3xl': TokenSetStatus.ENABLED,
	},
};

export const mockDensityThemeWithBreakpointTokenSets: ThemeObject = {
	id: 'test-density-breakpoint-theme',
	name: 'Test Density M',
	group: ThemeGroups.densities,
	selectedTokenSets: {
		'core/dimensions': TokenSetStatus.SOURCE,
		'semantic/densities/spacious': TokenSetStatus.ENABLED,
		'semantic/densities/spacious-m': TokenSetStatus.ENABLED,
	},
};

// Mock themes for edge cases
export const mockEmptyThemes: ThemeObject[] = [];

export const mockSingleDensityTheme: ThemeObject[] = [
	{
		id: 'single-density',
		name: 'Single Density XS-S',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
		},
	},
];

export const mockSingleComponentTheme: ThemeObject[] = [
	{
		id: 'single-component',
		name: 'Single Component XS-S',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'components/default/button': TokenSetStatus.ENABLED,
		},
	},
];

// Mock themes with names that have no whitespace (to test the else branch of densityThemeName.indexOf(' ') > 0)
export const mockDensityThemeNoWhitespace: ThemeObject[] = [
	{
		id: 'density-spacious-no-space',
		name: 'Spacious',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
		},
	},
];

export const mockComponentThemeNoWhitespace: ThemeObject[] = [
	{
		id: 'component-spacious-no-space',
		name: 'Spacious',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'core/dimensions': TokenSetStatus.SOURCE,
			'core/grid': TokenSetStatus.SOURCE,
			'core/motion': TokenSetStatus.SOURCE,
			'core/typography': TokenSetStatus.SOURCE,
			'semantic/color-schemes/light': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.SOURCE,
			'semantic/motion/lively': TokenSetStatus.SOURCE,
			'semantic/combined/composites': TokenSetStatus.SOURCE,
			'partials/default/icon': TokenSetStatus.ENABLED,
			'partials/default/indicator': TokenSetStatus.ENABLED,
			'partials/default/info': TokenSetStatus.ENABLED,
			'partials/default/input-field': TokenSetStatus.ENABLED,
			'components/default/accordion': TokenSetStatus.ENABLED,
			'components/default/avatar': TokenSetStatus.ENABLED,
			'components/default/badge': TokenSetStatus.ENABLED,
			'components/default/button': TokenSetStatus.ENABLED,
			'components/default/divider': TokenSetStatus.ENABLED,
			'components/default/dropdown': TokenSetStatus.ENABLED,
			'components/default/form-field': TokenSetStatus.ENABLED,
			'components/default/list': TokenSetStatus.ENABLED,
			'components/default/radio-button': TokenSetStatus.ENABLED,
			'components/default/segmented-control': TokenSetStatus.ENABLED,
			'components/default/switch': TokenSetStatus.ENABLED,
			'components/default/tab': TokenSetStatus.ENABLED,
			'components/default/tag': TokenSetStatus.ENABLED,
			'components/default/tile': TokenSetStatus.ENABLED,
			'components/default/toggle-button': TokenSetStatus.ENABLED,
			'components/default/tab-xs': TokenSetStatus.ENABLED,
			'components/default/tab-s': TokenSetStatus.ENABLED,
			'components/default/tab-m': TokenSetStatus.ENABLED,
			'components/default/tab-l': TokenSetStatus.ENABLED,
			'components/default/tab-xl': TokenSetStatus.ENABLED,
			'components/default/tab-2xl': TokenSetStatus.ENABLED,
			'components/default/tab-3xl': TokenSetStatus.ENABLED,
		},
	},
];

export const mockThemesNoWhitespace: ThemeObject[] = [
	...mockOtherThemes,
	...mockDensityThemeNoWhitespace,
	...mockComponentThemeNoWhitespace,
];

export const mockThemesWithoutMatch: ThemeObject[] = [
	{
		id: 'density-no-match',
		name: 'No Match Density',
		group: ThemeGroups.densities,
		selectedTokenSets: {
			'core/dimensions': TokenSetStatus.SOURCE,
			'semantic/densities/spacious': TokenSetStatus.ENABLED,
		},
	},
	{
		id: 'component-no-match',
		name: 'Different Component',
		group: ThemeGroups.components,
		selectedTokenSets: {
			'core/colors': TokenSetStatus.SOURCE,
			'components/default/button': TokenSetStatus.ENABLED,
		},
	},
];

export const mockThemesWithLargeBreakpoint: ThemeObject[] = [
	{
		id: 'density-xxxxl',
		name: 'Spacious-XXXXL',
		selectedTokenSets: {
			'a1/densities/spacious-xxxxl': TokenSetStatus.ENABLED,
		},
		group: ThemeGroups.densities,
	},
	{
		id: 'component-xs',
		name: 'XS',
		selectedTokenSets: {
			'a1/components/xs': TokenSetStatus.ENABLED,
		},
		group: ThemeGroups.components,
	},
];

export const mockThemesWithBreakpointHierarchyMismatch: ThemeObject[] = [
	{
		id: 'density-xs',
		name: 'Spacious XS',
		selectedTokenSets: {
			'a1/core-xs': TokenSetStatus.ENABLED,
		},
		group: ThemeGroups.densities,
	},
	{
		id: 'component-spacious',
		name: 'Spacious',
		selectedTokenSets: {
			// 2xl comes AFTER xs in hierarchy, so should trigger the else branch
			// where indexOf(2xl) > indexOf(xs), causing it to be filtered out
			'a1/component-2xl': TokenSetStatus.ENABLED,
		},
		group: ThemeGroups.components,
	},
];

// Helper function to create deep copy of themes
export const createDeepCopyOfThemes = (themes: ThemeObject[]): ThemeObject[] => JSON.parse(JSON.stringify(themes));

// Helper function to find themes by group
export const findThemesByGroup = (themes: ThemeObject[], group: ThemeGroups): ThemeObject[] =>
	themes.filter((theme: ThemeObject) => theme.group === group);

// Helper function to count combined themes
export const countCombinedThemes = (themes: ThemeObject[]): number =>
	themes.filter((theme: ThemeObject) => theme.group === ThemeGroups.componentDensities).length;
